env:
  PKG_NAME: pgx-uuidv7 # TODO must be converted from EXT_NAME
name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-linux-gnu:
    name: Build & Release for linux
    strategy:
      fail-fast: false
      matrix:
        pgVersion:
        - 16
        - 17
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Package
        run: |
          make build PG_VERSION=${{ matrix.pgVersion }}

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --draft \
            --title "${{ github.ref_name }}" \
            --generate-notes \
            ./target/${{ env.PKG_NAME }}-${{ matrix.pgVersion }}-amd64-linux-gnu.deb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
