env:
  PKG_NAME: pgx-uuidv7 # TODO must be converted from EXT_NAME
name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-linux-gnu:
    name: Build & Release for linux
    strategy:
      fail-fast: false
      matrix:
        pgVersion:
        - 16
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Package
        run: |
          make build PG_VERSION=${{ matrix.pgVersion }}

      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT_FOR_RELEASE }}
          draft: true
          # TODO artifact name shoud be changed and passed from build step
          artifacts: ./target/${{ env.PKG_NAME }}-${{ matrix.pgVersion }}-${{ matrix.arch }}-linux-gnu.deb
          artifactContentType: application/vnd.debian.binary-package
          bodyFile: ./RELEASE_NOTE.md
