env:
  EXT_NAME: pgx_uuidv7
  EXT_VERSION: 0.1.0
  PKG_NAME: pgx-uuidv7
  PGRX_VERSION: 0.11.2
name: Release
on:
  push:
    tags:
      - 'v*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-linux-gnu:
    name: Build & Release for linux
    strategy:
      fail-fast: false
      matrix:
        pgVersion:
        - 16
        runner:
        - ubuntu-22.04
        arch:
        - amd64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Package
        run: |
          make build  \
            PG_VERSION=${{ matrix.pgVersion }}  \
            EXT_NAME=$${{ env.EXT_NAME }} \
            EXT_VERSION=${{ env.EXT_VERSION }}  \
            ARCH=${{ matrix.arch }} \
            PKG_NAME=${{ env.PKG_NAME }}
            PG_VERSION=${{ matrix.pgVersion }}  \
            PGRX_VERSION=${{ env.PGRX_VERSION }}

      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT_FOR_RELEASE }}
          draft: true
          artifacts: ./target/${{ env.PKG_NAME }}-${{ matrix.pgVersion }}-${{ matrix.arch }}-linux-gnu.deb
          artifactContentType: application/vnd.debian.binary-package
          bodyFile: ./RELEASE_NOTE.md
