env:
  PKG_NAME: pgx-uuidv7 # TODO must be converted from EXT_NAME
name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  
jobs:
  build-packages:
    name: Build packages for PostgreSQL ${{ matrix.pgVersion }} on Debian ${{ matrix.debianCodename }}
    strategy:
      fail-fast: false
      matrix:
        debianCodename:
          - bullseye
          - bookworm
          - 13_trixie
        pgVersion:
        - 17
        - 18
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run tests
        run: |
          make test PG_VERSION=${{ matrix.pgVersion }}
      - name: Build Package
        run: |
          make build PG_VERSION=${{ matrix.pgVersion }} DEBIAN_CODENAME=${{ matrix.debianCodename }}
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: pgx-uuidv7-${{ matrix.pgVersion }}-amd64-linux-gnu.deb
          path: ./target/${{ env.PKG_NAME }}-pg${{ matrix.pgVersion }}-amd64-${{ matrix.debianCodename }}-gnu.deb
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: build-packages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download all packages
        uses: actions/download-artifact@v5
        with:
          path: ./packages
          pattern: pgx-uuidv7-*
          merge-multiple: true
      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --draft \
            --title "${{ github.ref_name }}" \
            --generate-notes \
            ./packages/*.deb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
