name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test PostgreSQL ${{ matrix.pgVersion }}
    strategy:
      fail-fast: false
      matrix:
        pgVersion:
          - 17
          - 18
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run tests
        run: |
          make test PG_VERSION=${{ matrix.pgVersion }}
